library(dplyr)
data_table <- read.csv(file='Desktop/gitfolder/R_analysis/Challenge/MechaCar_mpg.csv',check.names=F,stringsAsFactors = F)
View(data_table)
lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD,data=data_table)
summary(lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD,data=data_table))
coil_table <- read.csv(file='Desktop/gitfolder/R_analysis/Challenge/Suspension_Coil.csv',check.names=F,stringsAsFactors = F)
summarize_coil <- coil_table %>% summarize(Mean=mean(PSI), Median=median(PSI), Variance=var(PSI), SD=sd(PSI, na.rm=FALSE), .groups = 'keep')
lot_summary <- coil_table %>% group_by(Manufacturing_Lot) %>% summarize(Mean=mean(PSI), Median=median(PSI), Variance=var(PSI), SD=sd(PSI, na.rm=FALSE), .groups = 'keep')
t.test(coil_table$PSI,mu=1500)
t.test(subset(coil_table,Manufacturing_Lot=="Lot1")$PSI,mu=1500)
t.test(subset(coil_table,Manufacturing_Lot=="Lot2")$PSI,mu=1500)
t.test(subset(coil_table,Manufacturing_Lot=="Lot3")$PSI,mu=1500)
